name = "your-project-name"
type = "javascript"

[site]
bucket = "./dist"
entry-point = "index.html"

[site.headers]
"surrogate-control" = "no-store"
"cache-control" = "no-store, no-cache, must-revalidate, proxy-revalidate"
"content-type" = "text/html; charset=utf-8"

[site.routes]
[site.routes.api]
  pattern = "/api/*"
  headers = { "cache-control" = "no-store, no-cache, must-revalidate, proxy-revalidate" }

[site.routes.register]
  pattern = "/register"
  methods = ["GET", "HEAD", "POST", "OPTIONS"]
  headers = { "cache-control" = "no-store, no-cache, must-revalidate, proxy-revalidate" }

[site.routes.signin]
  pattern = "/signin"
  methods = ["GET", "HEAD", "POST", "OPTIONS"]
  headers = { "cache-control" = "no-store, no-cache, must-revalidate, proxy-revalidate" }

[build]
command = "astro build"

[build.upload]
dir = "./dist"