name = "astro-shadcn"
compatibility_date = "2024-09-25"

[build]
command = "cd web && bun install && bun run build"
cwd = ""
watch_dir = "web"

[build.upload]
format = "directory"
dir = "web/dist"

[[env_vars]]
name = "NODE_VERSION"
value = "20"
