// Re-export all types
export * from './business';
export * from './chat';
export * from './navigation';
export * from './seo';
export * from './contact';
export * from './i18n';
export * from './page'; 
export * from './schema'; 
